export const DASHBOARD_CONFIG = Object.freeze({
  mode: "verified",
  reportingEndpoint: "./data/reporting_status.json",
  kajabiStatusEndpoint: "/api/kajabi/status",
  reportingTimezone: "Australia/Melbourne",
  competitorDataRoot: "https://raw.githubusercontent.com/tokipaulo19/arsc-instagram-benchmarking/main",
  targetHandle: "givingtablebylilianasanelli",
  portfolioAccounts: [
    { handle: "givingtablebylilianasanelli", name: "The Giving Table" },
    { handle: "perfecteventsoz", name: "Perfect Events Group" },
    { handle: "empowherfund", name: "EmpowHER Fund" },
  ],
  fetchTimeoutMs: 12000,
  freshnessThresholdHours: {
    meta: 8,
    manychat: 8,
    ga4: 12,
    meta_ads: 12,
    competitors: 192,
  },
  insights: {
    minimumPostsForPillarComparison: 3,
    minimumMaturePostAgeHours: 72,
    meaningfulRelativeDifferencePercent: 15,
  },
  pillars: [
    "Giving",
    "Business and Leadership Growth",
    "Connection",
  ],
});

export const CONTENT_COLUMNS = [
  { key: "title", label: "Post", type: "text" },
  { key: "platform", label: "Platform", type: "text" },
  { key: "published_at", label: "Published", type: "date" },
  { key: "maturity", label: "Maturity", type: "text" },
  { key: "primary_pillar", label: "Primary pillar", type: "text" },
  { key: "secondary_pillars", label: "Secondary pillar(s)", type: "text" },
  { key: "format", label: "Format", type: "text" },
  { key: "campaign_slug", label: "Campaign", type: "text" },
  { key: "cta_keyword", label: "CTA", type: "text" },
  { key: "likes", label: "Likes", type: "number" },
  { key: "comments", label: "Comments", type: "number" },
  { key: "shares", label: "Shares", type: "number" },
  { key: "saves", label: "Saves", type: "number" },
  { key: "reach", label: "Reach", type: "number" },
  { key: "impressions", label: "Impressions", type: "number" },
  { key: "views", label: "Views", type: "number" },
  { key: "video_views", label: "Video views", type: "number" },
  { key: "completion_rate", label: "Completion", type: "percent" },
  { key: "engagement_rate", label: "Engagement", type: "percent" },
  { key: "share_rate", label: "Share rate", type: "percent" },
  { key: "save_rate", label: "Save rate", type: "percent" },
  { key: "follows_attributed", label: "Follows", type: "number" },
  { key: "dm_interactions", label: "DM interactions", type: "number" },
  { key: "automation_sends", label: "MC sends", type: "number" },
  { key: "manychat_ctr", label: "MC CTR", type: "percent" },
  { key: "contacts_captured", label: "Contacts", type: "number" },
  { key: "link_clicks", label: "Link clicks", type: "number" },
  { key: "sessions", label: "Social sessions", type: "number" },
  { key: "conversions", label: "Conversions", type: "number" },
];
